"use client";

// Client-side only: turns uploaded PDFs / images into rendered page images.
// PDFs are rasterised in the browser with pdf.js (no server-side parsing).

import type { PageImage } from "@/lib/types";

/** Longer edge of every rendered page, in px. */
const MAX_LONG_EDGE = 1600;
/** Never upscale a PDF page beyond 2x its native (72 dpi) size. */
const MAX_PDF_SCALE = 2;
/**
 * Same-origin copy of the pdf.js worker, generated by scripts/copy-pdf-worker.js
 * on `npm install`. Never a CDN — the worker must load with no external network.
 */
const PDF_WORKER_SRC = "/pdf.worker.min.mjs";

/**
 * The on-screen image (PageImage.dataUrl) is a lossless PNG. The copy sent to
 * the API routes (PageImage.base64) is a JPEG so that a multi-page answer sheet
 * stays under the 4.5 MB request-body limit of Vercel Functions. If the total
 * payload is still too big, pages are progressively re-encoded smaller.
 */
const UPLOAD_MIME = "image/jpeg";
const UPLOAD_QUALITY = 0.82;
const UPLOAD_BUDGET_CHARS = Math.floor(3.6 * 1024 * 1024);
const UPLOAD_FALLBACKS: { scale: number; quality: number }[] = [
  { scale: 1, quality: 0.7 },
  { scale: 1, quality: 0.6 },
  { scale: 0.8, quality: 0.7 },
  { scale: 0.65, quality: 0.7 },
  { scale: 0.5, quality: 0.7 },
  { scale: 0.4, quality: 0.6 },
];

/**
 * Converts every uploaded file (PDF or image) into a flat, sequential,
 * 0-indexed list of page images. Pages are concatenated in file order.
 */
export async function filesToPageImages(files: File[]): Promise<PageImage[]> {
  const canvases: HTMLCanvasElement[] = [];

  for (const file of files) {
    if (isPdfFile(file)) {
      canvases.push(...(await pdfToCanvases(file)));
    } else if (isImageFile(file)) {
      canvases.push(await imageToCanvas(file));
    } else {
      throw new Error(
        `"${file.name}" is not a PDF or image. Please upload PDF, PNG, JPEG or WEBP files.`,
      );
    }
  }

  if (canvases.length === 0) {
    throw new Error("No pages could be read from the uploaded files.");
  }

  const pages: PageImage[] = canvases.map((canvas, page) => ({
    page,
    dataUrl: canvas.toDataURL("image/png"),
    base64: encodeForUpload(canvas, 1, UPLOAD_QUALITY),
    mimeType: UPLOAD_MIME,
    width: canvas.width,
    height: canvas.height,
  }));

  return fitToUploadBudget(canvases, pages);
}

/**
 * Cheap page count for the upload card ("2MB • 2 pages"): PDF page count via
 * pdf.js metadata only (no rendering); each image file counts as one page.
 */
export async function countPages(files: File[]): Promise<number> {
  let total = 0;
  for (const file of files) {
    if (!isPdfFile(file)) {
      total += 1;
      continue;
    }
    const pdfjs = await import("pdfjs-dist");
    pdfjs.GlobalWorkerOptions.workerSrc = PDF_WORKER_SRC;
    const task = pdfjs.getDocument({ data: new Uint8Array(await file.arrayBuffer()) });
    try {
      total += (await task.promise).numPages;
    } finally {
      await task.destroy();
    }
  }
  return total;
}

function isPdfFile(file: File): boolean {
  return file.type === "application/pdf" || /\.pdf$/i.test(file.name);
}

function isImageFile(file: File): boolean {
  return (
    file.type.startsWith("image/") ||
    /\.(png|jpe?g|webp|gif|bmp|heic|heif)$/i.test(file.name)
  );
}

async function pdfToCanvases(file: File): Promise<HTMLCanvasElement[]> {
  const pdfjs = await import("pdfjs-dist");
  pdfjs.GlobalWorkerOptions.workerSrc = PDF_WORKER_SRC;

  const data = new Uint8Array(await file.arrayBuffer());
  const loadingTask = pdfjs.getDocument({ data });

  try {
    const doc = await loadingTask.promise;
    const out: HTMLCanvasElement[] = [];
    for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber++) {
      const page = await doc.getPage(pageNumber);
      const native = page.getViewport({ scale: 1 });
      const scale = Math.min(
        MAX_PDF_SCALE,
        MAX_LONG_EDGE / Math.max(native.width, native.height),
      );
      const viewport = page.getViewport({ scale });

      const canvas = document.createElement("canvas");
      canvas.width = Math.ceil(viewport.width);
      canvas.height = Math.ceil(viewport.height);

      await page.render({ canvas, viewport }).promise;
      page.cleanup();
      out.push(canvas);
    }
    return out;
  } catch (err) {
    throw new Error(describePdfError(file, err));
  } finally {
    // Releases the document and terminates the worker (v6 API: task-level destroy).
    await loadingTask.destroy();
  }
}

function describePdfError(file: File, err: unknown): string {
  const name = typeof err === "object" && err && "name" in err ? String(err.name) : "";
  const message = err instanceof Error ? err.message : String(err);
  if (name === "PasswordException") {
    return `"${file.name}" is password-protected. Remove the password and upload it again.`;
  }
  if (name === "InvalidPDFException") {
    return `"${file.name}" is not a valid PDF file.`;
  }
  if (/worker/i.test(message)) {
    return `The PDF renderer's worker (${PDF_WORKER_SRC}) could not be loaded. Run \`npm install\` to regenerate it, then reload the page.`;
  }
  return `Could not read "${file.name}": ${message}`;
}

async function imageToCanvas(file: File): Promise<HTMLCanvasElement> {
  const dataUrl = await readFileAsDataURL(file);
  const img = await loadImage(dataUrl, file.name);

  const longEdge = Math.max(img.naturalWidth, img.naturalHeight);
  const scale = longEdge > MAX_LONG_EDGE ? MAX_LONG_EDGE / longEdge : 1;

  const canvas = document.createElement("canvas");
  canvas.width = Math.max(1, Math.round(img.naturalWidth * scale));
  canvas.height = Math.max(1, Math.round(img.naturalHeight * scale));

  const ctx = get2dContext(canvas);
  // Photos with transparency would otherwise turn black in the JPEG copy.
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
  return canvas;
}

function readFileAsDataURL(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error(`Could not read "${file.name}".`));
    reader.readAsDataURL(file);
  });
}

function loadImage(src: string, name: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () =>
      reject(
        new Error(
          `Could not decode image "${name}". Use PNG, JPEG or WEBP (HEIC is not supported by most browsers).`,
        ),
      );
    img.src = src;
  });
}

function get2dContext(canvas: HTMLCanvasElement): CanvasRenderingContext2D {
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Your browser could not create a drawing canvas.");
  return ctx;
}

function stripDataUrlPrefix(dataUrl: string): string {
  return dataUrl.slice(dataUrl.indexOf(",") + 1);
}

/** JPEG-encodes a canvas (optionally downscaled) and returns raw base64. */
function encodeForUpload(
  canvas: HTMLCanvasElement,
  scale: number,
  quality: number,
): string {
  let source = canvas;
  if (scale < 1) {
    const scaled = document.createElement("canvas");
    scaled.width = Math.max(1, Math.round(canvas.width * scale));
    scaled.height = Math.max(1, Math.round(canvas.height * scale));
    const ctx = get2dContext(scaled);
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, scaled.width, scaled.height);
    ctx.drawImage(canvas, 0, 0, scaled.width, scaled.height);
    source = scaled;
  }
  return stripDataUrlPrefix(source.toDataURL(UPLOAD_MIME, quality));
}

function totalUploadChars(pages: PageImage[]): number {
  return pages.reduce((sum, p) => sum + p.base64.length, 0);
}

/**
 * Keeps the API payload (all pages' base64) under UPLOAD_BUDGET_CHARS by
 * re-encoding at lower quality / smaller size. On-screen PNGs are untouched.
 */
function fitToUploadBudget(
  canvases: HTMLCanvasElement[],
  pages: PageImage[],
): PageImage[] {
  if (totalUploadChars(pages) <= UPLOAD_BUDGET_CHARS) return pages;

  let best = pages;
  for (const { scale, quality } of UPLOAD_FALLBACKS) {
    best = pages.map((p, i) => ({
      ...p,
      base64: encodeForUpload(canvases[i], scale, quality),
    }));
    if (totalUploadChars(best) <= UPLOAD_BUDGET_CHARS) return best;
  }
  // Best effort — the API route / platform reports a clear error if still too large.
  return best;
}
